In [1]:
import numpy as np

def cumulative_mean_2d(A):
    """  
    A: np.array[num_row, num_column]        --- матрица-аргумент
    return S: np.array[num_row, num_column] --- выходная матрица кумулятивных сумм

    Функция принимает на вход матрицу A размерностью n x m и возвращает 
    матрицу с той же размерностью n x m, i-ая строчка которой есть последовательность 
    кумулятивных сумм элементов i-ой строки матрицы A

    В реализации этой функции необходимо использовать функционал пакета numpy

    """ 
    cumsum_array = np.cumsum(A, axis=1, dtype=float)
    
    print(A)
    print(A.shape)
    print(cumsum_array)
    
    for i in range(len(cumsum_array)):
        for j in range(len(cumsum_array[i])):
            cumsum_array[i][j] = cumsum_array[i][j] / (j + 1)

    result = cumsum_array
    return result

result = cumulative_mean_2d(np.array([[1, 2, 3], [4, 5, 6]]))
np.testing.assert_array_equal(result, np.array([[1. , 1.5, 2. ], [4. , 4.5, 5. ]]))

[[1 2 3]
 [4 5 6]]
(2, 3)
[[ 1.  3.  6.]
 [ 4.  9. 15.]]
