In [1]:
# Задан одномерный numpy.array 𝑋. 

# Необходимо написать функцию transform, которая построит новый массив Y,
# где все элементы с нечетными индексами требуется заменить на число 1.
# Все элементы с четными индексами нужно возвести в куб.
# Затем записать элементы в обратном порядке относительно их позиций. 

# Функция должна вернуть numpy.array того же размера, что и X.

# Пример работы функции:
# X = np.array([3, 1, 4, -1, 2, 3, 0])
# Y = transform(X)
# Y  # array([27, 1, 64, 1, 8, 1, 0])

import numpy as np

def transform(X):
    
    result = #YOUR CODE
    return resultray
    return result

X = np.array([3, 1, 4, -1, 2, 3, 0])
result = transform(X)
np.testing.assert_array_equal(result, array([27, 1, 64, 1, 8, 1, 0]))

[[1 2 3]
 [4 5 6]]
(2, 3)
[[ 1.  3.  6.]
 [ 4.  9. 15.]]
